export function useConstants() {
  const STATUS_OPEN = "STATUS_OPEN";
  const STATUS_SUBMIT_BY_PETUGAS = "STATUS_SUBMIT_BY_PETUGAS";
  const STATUS_REJECTED_BY_PETUGAS = "STATUS_REJECTED_BY_PETUGAS";
  const STATUS_APPROVED_BY_PENGAWAS = "STATUS_APPROVED_BY_PENGAWAS";
  const STATUS_REJECTED_BY_ADMIN = "STATUS_REJECTED_BY_ADMIN";
  const STATUS_APPROVED_BY_ADMIN = "STATUS_APPROVED_BY_ADMIN";

  const LEVEL_REKAP = {
    LEVEL_REKAP_SLS: "SLS",
    LEVEL_REKAP_BS: "Blok Sensus",
    LEVEL_REKAP_DESA: "Desa",
    LEVEL_REKAP_DESA_KELURAHAN: "Desa/Kelurahan",
    LEVEL_REKAP_KECAMATAN: "Kecamatan",
    LEVEL_REKAP_KABUPATEN: "Kabupaten/Kota",
    LEVEL_REKAP_PROVINSI: "Provinsi",
  };

  const LEVEL_ASSIGNMENT = {
    LEVEL_ASSIGNMENT_PENDUDUK: "Penduduk",
    LEVEL_ASSIGNMENT_UNIT_USAHA: "Unit Usaha",
    LEVEL_ASSIGNMENT_PERUSAHAAN: "Perusahaan",
    LEVEL_ASSIGNMENT_RUMAH_TANGGA: "Rumah Tangga",
    LEVEL_ASSIGNMENT_KEPALA_KELUARGA: "Kepala Keluarga",
    LEVEL_ASSIGNMENT_SLS: "SLS",
    LEVEL_ASSIGNMENT_DESA: "Desa",
    LEVEL_ASSIGNMENT_DESA_KELURAHAN: "Desa/Kelurahan",
    LEVEL_ASSIGNMENT_KECAMATAN: "Kecamatan",
  };

  const LEVEL_UNIT_OBSERVASI = {
    LEVEL_UNIT_OBSERVASI_PENDUDUK: "Penduduk",
    LEVEL_UNIT_OBSERVASI_UNIT_USAHA: "Unit Usaha",
    LEVEL_UNIT_OBSERVASI_PERUSAHAAN: "Perusahaan",
    LEVEL_UNIT_OBSERVASI_RUMAH_TANGGA: "Rumah Tangga",
    LEVEL_UNIT_OBSERVASI_KEPALA_KELUARGA: "Kepala Keluarga",
    LEVEL_UNIT_OBSERVASI_SLS: "SLS",
    LEVEL_UNIT_OBSERVASI_DESA: "Desa",
    LEVEL_UNIT_OBSERVASI_DESA_KELURAHAN: "Desa/Kelurahan",
  };

  const LEVEL_UNIT_SAMPEL = {
    LEVEL_UNIT_SAMPEL_PENDUDUK: "Penduduk",
    LEVEL_UNIT_SAMPEL_UNIT_USAHA: "Unit Usaha",
    LEVEL_UNIT_SAMPEL_PERUSAHAAN: "Perusahaan",
    LEVEL_UNIT_SAMPEL_KEPALA_KELUARGA: "Kepala Keluarga",
    LEVEL_UNIT_SAMPEL_RUMAH_TANGGA: "Rumah Tangga",
    LEVEL_UNIT_SAMPEL_SLS: "SLS",
    LEVEL_UNIT_SAMPEL_DESA: "Desa",
  };

  const JENIS_FREKUENSI = {
    JENIS_FREKEUNSI_TAHUN: "Tahunan",
    JENIS_FREKEUNSI_SEMESTER: "Semesteran",
    JENIS_FREKEUNSI_TRIWULAN: "Triwulanan",
    JENIS_FREKEUNSI_BULAN: "Bulanan",
    JENIS_FREKEUNSI_ADHOC: "Ad-Hoc",
  };

  const JENIS_TEST = {
    JENIS_TEST_VALID_IF: "Valid If",
    JENIS_TEST_SHOW_IF: "Show If",
    JENIS_TEST_REQUIRED_IF: "Required If",
    JENIS_TEST_TOGGLER: "Toggler",
  };

  const JENIS_USER = {
    JENIS_USER_ORGANIK: "Organik",
    JENIS_USER_NON_ORGANIK: "Orgamik",
  };

  const LEVEL_WILAYAH = {
    LEVEL_WILAYAH_SLS: "SLS",
    LEVEL_WILAYAH_BS: "Blok Sensus",
    LEVEL_WILAYAH_DESA_KELURAHAN: "Desa/Kelurahan",
    LEVEL_WILAYAH_DESA: "Desa",
    LEVEL_WILAYAH_KECAMATAN: "Kecamatan",
    LEVEL_WILAYAH_KABUPATEN: "Kabupaten/Kota",
    LEVEL_WILAYAH_PROVINSI: "Provinsi",
  };

  const ROLE_ADMIN_SATUAN_KERJA = {
    LEVEL_WILAYAH_DESA_KELURAHAN: "admin_desa",
    LEVEL_WILAYAH_DESA: "admin_desa",
    LEVEL_WILAYAH_KECAMATAN: "admin_kecamatan",
    LEVEL_WILAYAH_KABUPATEN_KOTA: "admin_kako",
    LEVEL_WILAYAH_PROVINSI: "admin_provinsi",
  };

  const JABATAN_LEVEL_1 = {
    JABATAN_LEVEL_1_PETUGAS_PENDATAAN_LAPANGAN: "PPL",
    JABATAN_LEVEL_1_PETUGAS_PEMERIKSA_LAPANGAN: "PML",
    JABATAN_LEVEL_1_KOSEKA: "Koseka",
  };

  const JABATAN_LEVEL_2 = {
    JABATAN_LEVEL_2_PETUGAS_PEMERIKSA_LAPANGAN: "PML",
    JABATAN_LEVEL_2_KOSEKA: "Koseka",
  };

  const JABATAN_LEVEL_3 = {
    JABATAN_LEVEL_3_KOSEKA: "Koseka",
  };

  const LEVEL_PENDATAAN = {
    LEVEL_PENDATAAN_SENSUS: "Sensus",
    LEVEL_PENDATAAN_SURVEI: "Survei",
  };

  const VERSI_TEMPLATE = {
    VERSI_TEMPLATE_LATEST: "Terbaru",
    VERSI_TEMPLATE_OLD: "Lama",
  };
  return {
    STATUS_OPEN,
    STATUS_SUBMIT_BY_PETUGAS,
    STATUS_REJECTED_BY_PETUGAS,
    STATUS_APPROVED_BY_PENGAWAS,
    STATUS_REJECTED_BY_ADMIN,
    STATUS_APPROVED_BY_ADMIN,
    LEVEL_REKAP,
    LEVEL_ASSIGNMENT,
    LEVEL_UNIT_OBSERVASI,
    LEVEL_UNIT_SAMPEL,
    JENIS_FREKUENSI,
    JENIS_TEST,
    JENIS_USER,
    LEVEL_WILAYAH,
    ROLE_ADMIN_SATUAN_KERJA,
    JABATAN_LEVEL_1,
    JABATAN_LEVEL_2,
    JABATAN_LEVEL_3,
    LEVEL_PENDATAAN,
    VERSI_TEMPLATE,
  };
}
